### PR TITLE
Issue 8 localization 2

### LINKED ISSUE #8: Localization issue in datecomponents.DateComponents view
I found a weird bug in `DateComponents` on branch 2.1.x (Plone 4.2) and 2.2.x (Plone 4.3).
On master the view had been removed so I don't know if this can happen also on Plone 5.

Issue happen at [that line] (https://github.com/plone/plone.app.form/blob/f00d3d179f34b52ab9f5c1fc8c7c4247edd09c31/plone/app/form/widgets/datecomponents.py#L218) where the current result from a call to `date.strftime("%p")` is compared to `"AM"` on `"PM"`:

    if x==p and not default:
        ...

But when some locales are set (for example IT_it, or DE_de) the call to `.format` will return `"am"` or `"pm"` (lowercase).
Normally Plone or buildout do not set locales directly but some 3rd party code can do this. For example: installing collective.flowplayer will also install the evil `hachoir_core` that call `locale.setlocale(locale.LC_ALL, "")` somewhere.

Apart the way to reproduce the issue, I think that a case insensitive version can make this code more robust:

    if x.lower()==p.lower() and not default:
        ...

Another way to test the issue simply using python:

    >>> from datetime import datetime
    >>> import locale
    >>> datetime.now().strftime("%p")
    'PM'
    >>> locale.setlocale(locale.LC_TIME, "IT_it")
    'IT_it'
    >>> datetime.now().strftime("%p")
    'pm'

Any thought? If is OK I'd like to make a PR for this.

### PR DESCRIPTION
**Pull request by gforcada**
Tries to fix #8, second attempt to merge #10.

Please test the code on the pull request job **before** merging.

### CODE REVIEW

**Comment by gforcada** [comment]
@keul here you have a new branch with your changes and my fixes.

Tests are running here: http://jenkins.plone.org/job/pull-request/99

**Comment by gforcada** [comment]
@keul sorry, the pull request job at jenkins.plone.org is only targetting plone 5 so we can not test this pull request before merging right now...

**Comment by keul** [comment]
@gforcada sorry I'm lost-in-jenkins. You need some tests on the branch?

**Comment by gforcada** [comment]
@keul yesterday I  was trying to create a pull request job for 4.3 but doing two, three or four things at the same time is never a good idea, so I didn't finish it. I will try to have them ready today.

So basically the problem to test this pull request on jenkins is that we lack a pull request job like the one we have but for plone 4.3 not for plone 5 as the current one is for.

**Comment by gforcada** [comment]
It took long, but finally they are running: http://jenkins.plone.org/view/All/job/pull-request-4.3/8

Thought this is only testing Plone 4.3 with Python 2.7, Python 2.6 is still not tested.

**Comment by keul** [comment]
@gforcada it seems tests are not passed :cry: 
Your new PR still works for me.

**Comment by gforcada** [comment]
Sorry for taking me sooooo long, hopefully now tests do pass: http://jenkins.plone.org/view/All/job/pull-request-4.3/11

The unrelated errors, both Robot Framework ones actually, most probably were there before...

**Comment by gforcada** [comment]
Sorry my mistake ... let's see now: http://jenkins.plone.org/view/All/job/pull-request-4.3/12/

**Comment by mauritsvanrees** [comment]
New Jenkins job: http://jenkins.plone.org/view/All/job/pull-request-4.3/40/

**Comment by jensens** [comment]
This Pull Request has stalled for a while now and is closed. If you care about this Pull Request please reopen at any time.

**Pull request closed without merging**
