### PR TITLE
Issue 8 localization

### PR DESCRIPTION
**Pull request by keul**
See #8

### CODE REVIEW

**Comment by jensens** [comment]
test runs here http://jenkins.plone.org/view/All/job/pull-request/90/

**Comment by jensens** [comment]
test runs here http://jenkins.plone.org/view/All/job/pull-request/92/

**Comment by jensens** [comment]
oh, this is the 2.2 branch youre targeting on? whats with master?

**Comment by keul** [comment]
@jensens  I didn't find this view on master, no bloody idea if Plone 5 suffer this bug but the date selection is totally changed.

**Comment by jensens** [comment]
in this case i do a merge now and check jenkins tomorrow...

**Comment by keul** [comment]
@gforcada  uhmmm... that's weird. Sorry.
Do you need some help fixing it? The branch has been deleted

**Comment by jensens** [comment]
branch restored

**Comment by gforcada** [comment]
I finally got around to update our nodes and I pushed this: https://github.com/plone/plone.app.form/commit/ba1e08766dad6c213e70ac604fbe5f66e43448fc jenkins is running, let's see.

**Comment by gforcada** [comment]
@keul I can not reproduce your original issue locally, specially the python interactive session that you pasted, not only IT_it does not work (I'm on linux, same as jenkins) but on top of that if I fix the locale I get an empty string instead of a lowercase values for am/pm.

```
>>> import locale
>>> from datetime import datetime
>>> from datetime import timedelta

>>> datetime.now()
datetime.datetime(2015, 4, 27, 21, 43, 19, 33825)
>>> datetime.now() + timedelta(hours=9)
datetime.datetime(2015, 4, 28, 6, 43, 38, 119491)

>>> datetime.now().strftime("%p")
'PM'
>>> locale.setlocale(locale.LC_TIME, "IT_it")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
>>> locale.setlocale(locale.LC_TIME, "it_IT")
'it_IT'
>>> datetime.now().strftime("%p")
''
>>> locale.setlocale(locale.LC_TIME, "en_US")
'en_US'
>>> datetime.now().strftime("%p")
'PM'
>>> locale.setlocale(locale.LC_TIME, "de_DE")
'de_DE'
>>> datetime.now().strftime("%p")
''
>>> datetime.now() + timedelta(hours=9)
datetime.datetime(2015, 4, 28, 6, 38, 13, 147529)
>>> (datetime.now() + timedelta(hours=9)).strftime("%p")
''
```

I will revert until it's properly fixed.

@jensens please *don't* merge pull requests if the pull request jenkins job already says that there are errors... that's what we created that jenkins job for to begin with.

**Pull request merged**
